export const getFeed = () => ({
  name: "Liko Chien",
  contact: {
    phone: "+44 7873 635073",
    email: "clwork1324@gmail.com",
    location: "London, UK",
  },
  experience: [
    {
      company: "California Umbrella",
      position: "Senior Frontend Developer",
      duration: "02/2024 - Present",
      achievements: [
        "Optimized CI/CD pipeline with quality gates and linters, improving team efficiency.",
        "Reduced bundle size by 30% via code splitting and asset optimization.",
        "Enhanced application speed by identifying performance bottlenecks.",
        "Refactored Next.js B2B CMS codebase for improved maintainability.",
        "Used Sentry for error tracking and Istanbul for coverage.",
        "Streamlined API development with Swagger code generators.",
        "Created comprehensive documentation for cross-team collaboration.",
        "Implemented hybrid rendering for improved responsiveness.",
        "Integrated mock server CLI for frontend-backend separation.",
        "Used Playwright for E2E testing, enhancing cross-browser compatibility.",
      ],
    },
    {
      company: "Optoma",
      position: "Senior Frontend Developer",
      duration: "05/2023 - 02/2024",
      achievements: [
        "Migrated JavaScript to TypeScript, reducing type-related bugs by 75%.",
        "Decreased API errors by 60% through runtime validation.",
        "Developed Next.js CMS and OAM projects with internationalization.",
        "Integrated Stripe payment gateway for secure transactions.",
        "Optimized API performance via caching and request optimization.",
        "Implemented accessibility enhancements for user-friendly interfaces.",
        "Developed comprehensive unit tests using Jest.",
        "Reconstructed styling with Tailwind CSS, reducing CSS by 40%.",
        "Developed E2E tests with Cypress.",
      ],
    },
    {
      company: "Chia Sheng Land Registration Office",
      position: "Frontend Developer",
      duration: "01/2021 - 05/2023",
      achievements: [
        "Conducted Scrum and code reviews for improved collaboration.",
        "Improved data handling with React Hook Form and pagination.",
        "Collaborated with designers to build responsive platforms.",
        "Implemented React-Redux for optimized data flow.",
        "Used Styled Components for dynamic styles.",
        "Enhanced scalability with AWS Amplify.",
        "Integrated OAuth2, JWT, and WebSocket for security.",
      ],
    },
  ],
  skills: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "Node.js",
    "Redux",
    "React Query",
    "Zustand",
    "React Form Hook",
    "Zod",
    "Tailwind",
    "Styled Components",
    "MUI",
    "Mantine",
    "RWD",
    "Webpack",
    "Babel",
    "ESLint",
    "AWS",
    "GitHub Actions",
    "Bitbucket CI",
    "Jest",
    "Cypress",
    "Playwright",
  ],
  education: {
    institution: "Taiwan National University of Arts",
    degree: "Master Degree in Music Composition",
    graduationDate: "07/2018",
  },
});

export const greetingMsg = () => {
  return "Hey, welcome to my profile. Just a quick heads up, I'm here to provide information and assistance, but please keep in mind that this is not a live chat. If you have any questions, feel free to ask, and I'll do my best to help you out.";
};
